# SHASHA_DRUGZ/plugins/PREMIUM/assistant_guard.py
"""
assistant_guard.py
──────────────────
Auto-unban + auto-join the assistant userbot whenever a /play command is
issued in a group where the assistant is missing or banned.

THE ROOT FIX applied here:
  The old version used `app` (main bot) to check permissions and generate
  invite links. The main bot has NO admin rights in the group — only the
  deployed bot (client) does. So permission checks always returned False,
  and invite link generation always failed with ChatAdminRequired, which
  bubbled up as the false "make me admin" message.

  Now: all permission checks and invite link calls go through the deployed
  bot client that is actually an admin in the group.

Logic flow:
  1. Check assistant membership via the deployed bot client.
  2. MEMBER / ADMINISTRATOR / OWNER / RESTRICTED → already in, cache + return.
  3. BANNED → unban via deployed bot client, then join.
  4. None (not participant) → join via username, then via invite link
     generated by the deployed bot client.
  5. All steps fire-and-forget in a background task on /play.
"""
import asyncio
import logging
from functools import wraps
from pyrogram import Client, filters
from pyrogram.enums import ChatMemberStatus
from pyrogram.errors import (
    ChatAdminRequired,
    FloodWait,
    InviteHashExpired,
    InviteHashInvalid,
    InviteRequestSent,
    PeerIdInvalid,
    UserAlreadyParticipant,
    UserNotParticipant,
    ChatWriteForbidden,
    ChannelPrivate,
)
from pyrogram.types import Message
from SHASHA_DRUGZ import app
from SHASHA_DRUGZ.utils.database import get_assistant
# Import the deployed clients registry so we can get the right client instance
from SHASHA_DRUGZ.core.isolation import _current_bot_id

logger = logging.getLogger("assistant_guard")

# ── Confirmed-present cache (10 min TTL) ──────────────────────────────────────
_confirmed_chats: dict = {}
_RECHECK_SECONDS = 600


def _is_recently_confirmed(chat_id: int) -> bool:
    import time
    return (time.time() - _confirmed_chats.get(chat_id, 0)) < _RECHECK_SECONDS


def _mark_confirmed(chat_id: int):
    import time
    _confirmed_chats[chat_id] = time.time()


def _clear_confirmed(chat_id: int):
    _confirmed_chats.pop(chat_id, None)


# ── Get the deployed bot Client for the current context ───────────────────────
def _get_deployed_client() -> Client:
    """
    Returns the deployed bot Client instance for the current bot context.
    Falls back to `app` (main bot) if no deployed context is active.
    """
    try:
        from SHASHA_DRUGZ.plugins.PREMIUM.deploy import DEPLOYED_CLIENTS
        bot_id = _current_bot_id.get(None)
        if bot_id and bot_id in DEPLOYED_CLIENTS:
            return DEPLOYED_CLIENTS[bot_id]
    except Exception:
        pass
    return app


# ── Check membership status ───────────────────────────────────────────────────
async def _get_assistant_status(deployed_client: Client, chat_id: int, assistant_id: int):
    """
    Returns ChatMemberStatus or None (= not in chat).
    Uses the deployed bot client which has admin rights.
    """
    for client_to_try in (deployed_client, app):
        try:
            member = await client_to_try.get_chat_member(chat_id, assistant_id)
            return member.status
        except UserNotParticipant:
            return None
        except (PeerIdInvalid, ChannelPrivate, ChatWriteForbidden):
            return None
        except FloodWait as e:
            await asyncio.sleep(min(e.value, 10))
            return None
        except Exception:
            continue
    return None


# ── Unban via deployed client ─────────────────────────────────────────────────
async def _try_unban(deployed_client: Client, chat_id: int, assistant_id: int) -> bool:
    for client_to_try in (deployed_client, app):
        try:
            await client_to_try.unban_chat_member(chat_id, assistant_id)
            logger.info(f"[assistant_guard] Unbanned assistant {assistant_id} in {chat_id}")
            return True
        except ChatAdminRequired:
            continue
        except FloodWait as e:
            await asyncio.sleep(min(e.value, 10))
            return False
        except Exception as e:
            logger.debug(f"[assistant_guard] Unban attempt failed: {e}")
            continue
    logger.warning(f"[assistant_guard] Could not unban assistant in {chat_id}")
    return False


# ── Join via public username ───────────────────────────────────────────────────
async def _try_join_via_username(deployed_client: Client, userbot: Client, chat_id: int) -> bool:
    try:
        # Use deployed client to fetch chat info
        chat = await deployed_client.get_chat(chat_id)
        username = getattr(chat, "username", None)
        if not username:
            return False
        await userbot.join_chat(username)
        logger.info(f"[assistant_guard] Assistant joined {chat_id} via @{username}")
        return True
    except UserAlreadyParticipant:
        return True
    except InviteRequestSent:
        try:
            me = await userbot.get_me()
            await deployed_client.approve_chat_join_request(chat_id, me.id)
            return True
        except Exception:
            return False
    except FloodWait as e:
        await asyncio.sleep(min(e.value, 10))
        return False
    except Exception as e:
        logger.debug(f"[assistant_guard] Username join failed in {chat_id}: {e}")
        return False


# ── Join via invite link (generated by deployed client, not app) ──────────────
async def _try_join_via_invite(deployed_client: Client, userbot: Client, chat_id: int) -> bool:
    """
    THE KEY FIX: invite link is generated using `deployed_client` which has
    admin rights in the group, not `app` which has no rights.
    """
    invite_link = None

    # Try create_chat_invite_link first (deployed bot has admin rights)
    for client_to_try in (deployed_client, app):
        try:
            link_obj = await client_to_try.create_chat_invite_link(chat_id)
            invite_link = link_obj.invite_link
            break
        except Exception:
            pass

    # Fall back to permanent invite link
    if not invite_link:
        for client_to_try in (deployed_client, app):
            try:
                invite_link = await client_to_try.export_chat_invite_link(chat_id)
                break
            except Exception:
                pass

    if not invite_link:
        logger.debug(f"[assistant_guard] Could not generate any invite link for {chat_id}")
        return False

    try:
        await asyncio.sleep(1)
        await userbot.join_chat(invite_link)
        logger.info(f"[assistant_guard] Assistant joined {chat_id} via invite link")
        return True
    except UserAlreadyParticipant:
        return True
    except InviteRequestSent:
        try:
            me = await userbot.get_me()
            await deployed_client.approve_chat_join_request(chat_id, me.id)
            return True
        except Exception:
            return False
    except (InviteHashExpired, InviteHashInvalid):
        logger.warning(f"[assistant_guard] Invite link expired/invalid for {chat_id}")
        return False
    except FloodWait as e:
        await asyncio.sleep(min(e.value, 10))
        return False
    except Exception as e:
        logger.debug(f"[assistant_guard] Invite join failed in {chat_id}: {e}")
        return False


# ── CORE ──────────────────────────────────────────────────────────────────────
async def ensure_assistant_in_chat(chat_id: int) -> bool:
    """
    Silently ensure the assistant is present in the group.
    Uses the deployed bot client (has admin rights) for all API calls.
    """
    if _is_recently_confirmed(chat_id):
        return True

    # Get the deployed client that has admin rights in this group
    deployed_client = _get_deployed_client()

    try:
        userbot = await get_assistant(chat_id)
    except Exception as e:
        logger.warning(f"[assistant_guard] Could not get assistant for {chat_id}: {e}")
        return False

    assistant_id = userbot.id

    # ── Step 1: check status via deployed bot ─────────────────────────────────
    status = await _get_assistant_status(deployed_client, chat_id, assistant_id)

    if status in (
        ChatMemberStatus.MEMBER,
        ChatMemberStatus.ADMINISTRATOR,
        ChatMemberStatus.OWNER,
        ChatMemberStatus.RESTRICTED,  # in chat with limited perms — do NOT rejoin
    ):
        _mark_confirmed(chat_id)
        return True

    # ── Step 2: banned → unban via deployed client ────────────────────────────
    if status == ChatMemberStatus.BANNED:
        _clear_confirmed(chat_id)
        ok = await _try_unban(deployed_client, chat_id, assistant_id)
        if not ok:
            return False
        await asyncio.sleep(2)

    # ── Step 3: join ──────────────────────────────────────────────────────────
    _clear_confirmed(chat_id)

    if await _try_join_via_username(deployed_client, userbot, chat_id):
        _mark_confirmed(chat_id)
        return True

    if await _try_join_via_invite(deployed_client, userbot, chat_id):
        _mark_confirmed(chat_id)
        return True

    logger.warning(
        f"[assistant_guard] Could not join assistant into {chat_id} — "
        f"all methods exhausted."
    )
    return False


# ── PLAY COMMAND INTERCEPTOR ──────────────────────────────────────────────────
PLAY_COMMANDS = [
    "play", "vplay", "cplay", "cvplay",
    "playforce", "vplayforce", "cplayforce", "cvplayforce",
]


@app.on_message(
    filters.command(PLAY_COMMANDS, prefixes=["/", "!", "%", ".", "@", "#", ""])
    & filters.group,
    group=-10,
)
async def _play_assistant_guard(client: Client, message: Message):
    """Fire-and-forget: ensure assistant present before play handler runs."""
    asyncio.create_task(ensure_assistant_in_chat(message.chat.id))


# ── OPTIONAL DECORATOR ────────────────────────────────────────────────────────
def with_assistant_guard(func):
    """
    Awaits the guard before running the handler — use if you hit race conditions
    where pytgcalls tries to connect before the assistant is in the group.
    """
    @wraps(func)
    async def wrapper(client, message: Message, *args, **kwargs):
        guard_task = asyncio.create_task(ensure_assistant_in_chat(message.chat.id))
        try:
            result = await func(client, message, *args, **kwargs)
        finally:
            try:
                await guard_task
            except Exception as e:
                logger.debug(f"[assistant_guard] guard task error: {e}")
        return result
    return wrapper
